name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build Docker image
              run: docker build -t fizzbuzz .

            - name: Run unit tests
              run: docker run --rm fizzbuzz vendor/bin/phpunit --testsuite=unit

            - name: Run functional tests
              run: docker run --rm fizzbuzz vendor/bin/phpunit --testsuite=functional
